### PR TITLE
Port to python 3 and config update

### PR DESCRIPTION
**Pull request by nicolaselie**

### CODE REVIEW

**Comment by bskim45** [comment]
Hi, @nicolaselie!
Seems it has a problem with opening version.txt on Python 2.
How about using `io.open()` over `open()` and drop support 2.6 (https://docs.python.org/3/howto/pyporting.html)?

**Comment by nicolaselie** [comment]
Yes, you are right. Seems to be the correct way to do it

**Comment by bskim45** [comment]
Everything goes fine except [line 72](https://github.com/bskim45/ccleaner-auto-update/pull/1/files#diff-9bf88fd9b4b2109824bad4c288921b24R72).
Since file already opened with UTF-16, there's no need to wrap it with `unicode`.

**Comment by nicolaselie** [comment]
Yes, I apologize. I don't have a Windows Python 2 installed so I did not test the code.

**Comment by bskim45** [comment]
I just merged PR. Thanks @nicolaselie!

**Comment by nicolaselie** [comment]
As config was updated because website changed, maybe a new release is appropriate?

**Comment by bskim45** [comment]
[v0.4 released](https://github.com/bskim45/ccleaner-auto-update/releases/tag/v0.4)! Thanks again @nicolaselie

**Pull request merged**
